version: "3"

services:
  metric_app:
    build: .
    container_name: metric_app
    volumes:
      - /proc/meminfo:/proc/meminfo:ro
      - /proc/loadavg:/proc/loadavg:ro
      - /:/host:ro
      - /var/log/metrics:/app/logs
    env_file: .env
    
    restart: unless-stopped

